#!/bin/sh

set -eux

os="${1:-fedora}"
cd "${0%/*}"

../common/check-config

case "${os}" in
    fedora)
        containerfile='Containerfile'
        ;;
    arch)
        containerfile='Containerfile.arch'
        ;;
    *)
        echo "*** unknown variant ${os}"
        false
        ;;
esac

# https://github.com/containers/buildah/issues/5656
PODMAN_BUILD="podman build --no-cache"

cargo build --release

cp ../../target/release/cfsctl .
cp ../../target/release/composefs-setup-root extra/usr/lib/dracut/modules.d/37composefs/
CFSCTL='./cfsctl --repo tmp/sysroot/composefs'

rm -rf tmp
rm -rf tmp/efi tmp/sysroot/composefs/images
${CFSCTL} init --algorithm=fsverity-sha256-12

${PODMAN_BUILD} \
    --iidfile=tmp/base.iid \
    --target=base \
    -f "${containerfile}" \
    .

BASE_ID="$(cat tmp/base.iid)"
${CFSCTL} oci pull containers-storage:"${BASE_ID}"
BASE_KARG="$(${CFSCTL} oci composefs-digest-karg "@${BASE_ID}")"

${PODMAN_BUILD} \
    --iidfile=tmp/final.iid \
    --build-context=base="container-image://${BASE_ID}" \
    --build-arg=COMPOSEFS_KARG="${BASE_KARG}" \
    --label=containers.composefs.karg="${BASE_KARG}" \
    -f "${containerfile}" \
    .

FINAL_ID="$(cat tmp/final.iid)"
${CFSCTL} oci pull containers-storage:"${FINAL_ID}"
${CFSCTL} oci prepare-boot "@${FINAL_ID}" --bootdir tmp/efi

../common/install-systemd-boot
../common/make-image "${os}-uki-efi.qcow2"
